//
//  LoginRouter.swift
//  LTechTest
//
//  Created by Pavel21 on 08.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol LoginRoutingLogic {
    func routeToMainMenu()
}

protocol LoginDataPassing {
    var dataStore: LoginDataStore? { get }
}

class LoginRouter: NSObject, LoginRoutingLogic, LoginDataPassing {
    weak var viewController: LoginViewController?
    var dataStore: LoginDataStore?

// MARK: - Routing (navigating to other screens)

    func routeToMainMenu() {
        let storyboard = UIStoryboard(name: "MainMenuViewController", bundle: nil)
        let destinationVC = storyboard.instantiateViewController(withIdentifier: "MainMenuTabBarController")
        navigateToMainMenu(source: viewController!, destination: destinationVC)
    }

// MARK: - Navigation to other screen

    func navigateToMainMenu(source: LoginViewController, destination: UIViewController) {
        source.show(destination, sender: nil)
    }
}
