//
//  LoginModels.swift
//  LTechTest
//
//  Created by Pavel21 on 08.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Login
{
    // MARK: Use cases

    enum Something
    {
        struct Request
        {

        }

        struct Response
        {

        }

        struct ViewModel
        {

        }
    }
    
    enum Mask
    {
        struct Response
        {
            var mask: String?
        }
        
        struct ViewModel
        {
            var mask: String
            var code: String
        }
    }
    
    enum Login
    {
        struct Request
        {
            var phone: String
            var password: String
        }
        
        struct Response
        {
            var success: Bool
        }
        
        struct ViewModel
        {
            var success: Bool
        }
    }
}
