//
//  MainMenuRouter.swift
//  LTechTest
//
//  Created by Pavel21 on 12.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol MainMenuRoutingLogic {
}

protocol MainMenuDataPassing {
    var dataStore: MainMenuDataStore? { get }
}

class MainMenuRouter: NSObject, MainMenuRoutingLogic, MainMenuDataPassing {
    weak var viewController: MainMenuViewController?
    var dataStore: MainMenuDataStore?

}
