//
//  MainMenuPresenter.swift
//  LTechTest
//
//  Created by Pavel21 on 12.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MainMenuPresentationLogic {
    func presentSomething(response: MainMenu.Something.Response)
}

class MainMenuPresenter: MainMenuPresentationLogic {
    weak var viewController: MainMenuDisplayLogic?

    // MARK: Parse and calc respnse from MainMenuInteractor and send simple view model to MainMenuViewController to be displayed

    func presentSomething(response: MainMenu.Something.Response) {
        let viewModel = MainMenu.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
//
//    func presentSomethingElse(response: MainMenu.SomethingElse.Response) {
//        let viewModel = MainMenu.SomethingElse.ViewModel()
//        viewController?.displaySomethingElse(viewModel: viewModel)
//    }
}
