//
//  MainMenuInteractor.swift
//  LTechTest
//
//  Created by Pavel21 on 12.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit
import Alamofire
import SwiftyJSON

protocol MainMenuBusinessLogic {
    func loadData()
    func sortData(array: [MainMenu.CellData.CellData], sort: MainMenu.Sort.Sort)
}

protocol MainMenuDataStore {
    //var name: String { get set }
}

class MainMenuInteractor: MainMenuBusinessLogic, MainMenuDataStore {
    var presenter: MainMenuPresentationLogic?
    var worker: MainMenuWorker?
    


    // MARK: Do something (and send response to MainMenuPresenter)
    
    func loadData() {
                
        AF.request("http://dev-exam.l-tech.ru/api/v1/posts", method: .get).responseJSON { response in
            let value = response.value ?? ""
            let json = JSON(value)
            self.presenter?.presentLoadedData(data: json)
        }
    }
    
    func sortData(array: [MainMenu.CellData.CellData], sort: MainMenu.Sort.Sort) {
        self.presenter?.presentSortedData(array: array, sort: sort)
    }
}
