//
//  MainMenuModels.swift
//  LTechTest
//
//  Created by Pavel21 on 12.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainMenu
{
    // MARK: Use cases

    enum Something
    {
        struct Request
        {

        }

        struct Response
        {

        }

        struct ViewModel
        {

        }
    }
    
//    "id": 0,
//    "title": "Title 1",
//    "text": "Detailed Text 1",
//    "image": "http://l-tech.ru/image_1.jpg", "sort": 2,
//    "date": "2016-06-16 09:39:43"
    
    enum CellData
    {
        struct CellData
        {
            var id: String
            var title: String
            var text: String
            var image: String
            var sort: String
            var date: String
        }
    }
    
//    enum SomethingElse
//    {
//        struct Request
//        {
//
//        }
//
//        struct Response
//        {
//
//        }
//
//        struct ViewModel
//        {
//
//        }
//    }
}
