//
//  MainMenuModels.swift
//  LTechTest
//
//  Created by Pavel21 on 12.11.2022.
//  Copyright (c) 2022 ___ORGANIZATIONNAME___. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum MainMenu
{
    // MARK: Use cases

    enum CellData
    {
        struct CellData
        {
            var id: String
            var title: String
            var text: String
            var image: String
            var sort: Int
            var date: Date
            var stringDate: String
        }
    }
    
    enum Sort
    {
        struct Sort
        {
            var isSortedByDate: Bool
        }
    }

}
